Repository SUVID-18/tag_management, pull requests merged in 2023-04, with the labels that each got.

#16 요청 작업에 대한 구현 완료
  assets/images/swu_bluelogo.png
  assets/images/swu_horizontalLogo.png
  lib/view/login.dart
  lib/view/upload.dart
  pubspec.yaml
Labels: 화면 제작

#21 자동화 관련 문제 수정
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: 기능 개선

#23 NFC 모델링 작업 완료
  lib/model/nfc.dart
  pubspec.lock
  pubspec.yaml
  test/model_test.dart
Labels: 기능 개선

#27 uuid미지정 시 ''로 지정되는 문제 해결
  lib/model/nfc.dart
  test/model_test.dart
Labels: 버그

#29 자동화 테스트, 빌드 및 배포 적용
  .github/workflows/flutter-deploy.yaml
  .github/workflows/flutter-test.yaml
  .github/workflows/flutter_test.yaml
  .github/workflows/issue-commented.yaml
  .gitignore
Labels: 기능 개선
